2023-10-18 14:01:20.399 | ERROR    | core.exception:unicorn_exception_handler:64 - Not Found
2023-10-18 14:44:04.982 | ERROR    | core.exception:unicorn_exception_handler:64 - Not Found
2023-10-18 14:44:44.615 | ERROR    | core.exception:unicorn_exception_handler:64 - Not Found
2023-10-18 16:32:33.966 | ERROR    | core.exception:unicorn_exception_handler:64 - Not Found
2023-10-18 16:32:37.697 | ERROR    | core.exception:unicorn_exception_handler:64 - Not Found
2023-10-18 16:33:29.570 | ERROR    | core.exception:unicorn_exception_handler:64 - Not Found
2023-10-18 16:33:42.299 | ERROR    | core.exception:unicorn_exception_handler:64 - Not Found
2023-10-18 16:35:51.496 | ERROR    | core.exception:validation_exception_handler:81 - [{'type': 'int_type', 'loc': ('body', 'role_ids', 0), 'msg': 'Input should be a valid integer', 'input': None, 'url': 'https://errors.pydantic.dev/2.3/v/int_type'}]
2023-10-18 16:41:17.978 | ERROR    | core.exception:unicorn_exception_handler:64 - Not Found
2023-10-18 16:41:33.273 | ERROR    | core.exception:unicorn_exception_handler:64 - Not Found
2023-10-18 16:44:12.284 | ERROR    | core.exception:validation_exception_handler:81 - [{'type': 'int_type', 'loc': ('body', 'role_ids', 0), 'msg': 'Input should be a valid integer', 'input': None, 'url': 'https://errors.pydantic.dev/2.3/v/int_type'}]
2023-10-18 16:44:33.898 | ERROR    | core.exception:validation_exception_handler:81 - [{'type': 'int_type', 'loc': ('body', 'role_ids', 0), 'msg': 'Input should be a valid integer', 'input': None, 'url': 'https://errors.pydantic.dev/2.3/v/int_type'}]
2023-10-18 16:45:43.480 | ERROR    | core.exception:unicorn_exception_handler:64 - Not Found
2023-10-18 16:45:57.192 | ERROR    | core.exception:validation_exception_handler:81 - [{'type': 'int_type', 'loc': ('body', 'role_ids', 0), 'msg': 'Input should be a valid integer', 'input': None, 'url': 'https://errors.pydantic.dev/2.3/v/int_type'}]
2023-10-18 16:46:06.196 | ERROR    | core.exception:validation_exception_handler:81 - [{'type': 'int_type', 'loc': ('body', 'role_ids', 0), 'msg': 'Input should be a valid integer', 'input': None, 'url': 'https://errors.pydantic.dev/2.3/v/int_type'}]
2023-10-18 16:55:06.076 | ERROR    | core.exception:validation_exception_handler:81 - [{'type': 'int_type', 'loc': ('body', 'role_ids', 0), 'msg': 'Input should be a valid integer', 'input': None, 'url': 'https://errors.pydantic.dev/2.3/v/int_type'}]
2023-10-18 16:55:21.901 | ERROR    | core.exception:validation_exception_handler:81 - [{'type': 'int_type', 'loc': ('body', 'role_ids', 0), 'msg': 'Input should be a valid integer', 'input': None, 'url': 'https://errors.pydantic.dev/2.3/v/int_type'}]
2023-10-18 17:17:45.226 | ERROR    | core.exception:all_exception_handler:130 - Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed'}
2023-10-18 17:18:15.240 | ERROR    | core.exception:all_exception_handler:130 - Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed'}
2023-10-18 17:50:42.239 | ERROR    | core.exception:all_exception_handler:130 - Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed'}
2023-10-18 18:03:31.210 | ERROR    | core.exception:validation_exception_handler:81 - [{'type': 'int_type', 'loc': ('body', 'role_ids', 1), 'msg': 'Input should be a valid integer', 'input': None, 'url': 'https://errors.pydantic.dev/2.3/v/int_type'}]
2023-10-18 18:03:46.201 | ERROR    | core.exception:validation_exception_handler:81 - [{'type': 'int_type', 'loc': ('body', 'role_ids', 0), 'msg': 'Input should be a valid integer', 'input': None, 'url': 'https://errors.pydantic.dev/2.3/v/int_type'}]
2023-10-18 18:03:49.190 | ERROR    | core.exception:validation_exception_handler:81 - [{'type': 'int_type', 'loc': ('body', 'role_ids', 0), 'msg': 'Input should be a valid integer', 'input': None, 'url': 'https://errors.pydantic.dev/2.3/v/int_type'}]
2023-10-18 18:06:36.386 | ERROR    | core.exception:validation_exception_handler:81 - [{'type': 'int_type', 'loc': ('body', 'role_ids', 0), 'msg': 'Input should be a valid integer', 'input': None, 'url': 'https://errors.pydantic.dev/2.3/v/int_type'}]
2023-10-18 18:06:47.018 | ERROR    | core.exception:validation_exception_handler:81 - [{'type': 'int_type', 'loc': ('body', 'role_ids', 0), 'msg': 'Input should be a valid integer', 'input': None, 'url': 'https://errors.pydantic.dev/2.3/v/int_type'}]
